# Generated by Django 4.1.2 on 2022-12-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_page_link_category_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.page'),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
        migrations.AlterField(
            model_name='link',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.page'),
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.CharField(max_length=1000000)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.page')),
            ],
        ),
    ]
