# Generated by Django 4.1.2 on 2022-12-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_category_page_alter_link_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='page',
        ),
    ]
