# Generated by Django 4.1.2 on 2022-12-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_link_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.page'),
            preserve_default=False,
        ),
    ]
