# Generated by Django 4.1.2 on 2022-12-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_link_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='bio',
            field=models.CharField(default='Hello World!', max_length=10000),
            preserve_default=False,
        ),
    ]
