# Generated by Django 4.1.2 on 2022-12-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_page_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
