# Generated by Django 4.1.2 on 2022-12-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_link_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pic',
            field=models.ImageField(default='images/default.png', upload_to='images'),
        ),
    ]
