# Generated by Django 4.1.2 on 2022-12-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_page_views_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
