# Generated by Django 4.1.2 on 2022-12-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_page_views_delete_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='effect',
            field=models.CharField(default='raise', max_length=1000),
        ),
    ]
