# Generated by Django 4.1.2 on 2022-12-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_page_views_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='font',
            field=models.CharField(default='karla', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='colorscheme',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='effect',
            field=models.CharField(default='raise', max_length=100),
        ),
    ]
