# Generated by Django 4.1.2 on 2022-12-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_page_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='qr',
        ),
    ]
