# Generated by Django 4.1.2 on 2022-12-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_colorscheme_effect_font_page_view_style_and_more'),
        ('website', '0020_remove_page_qr'),
    ]

    operations = [
    ]
