# Generated by Django 4.1.2 on 2022-12-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_merge_20221227_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='backgroud',
        ),
        migrations.AddField(
            model_name='page',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
