# Generated by Django 4.1.2 on 2022-12-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_page_backgroud_page_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='background',
        ),
    ]
