# Generated by Django 4.1.2 on 2022-12-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_page_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
