# Generated by Django 4.1.2 on 2023-02-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_page_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='startpage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='startpage',
            field=models.BooleanField(default=False),
        ),
    ]
